Feature/testing
comp413-2017/RDFS pull request #25
Opened 2017-10-05 20:43 UTC by rzhang0720

This PR fixes some of the test cases that are currently in RDFS.

With the exception of **ReplicationTest** and **ReadWriteTest**, all the tests should be working. This behavior can be verified by building RDFS and then running `/home/rdfs/build/test/RunAllTests`

2017-10-05 20:47 UTC, LINKIWI requested changes
Please unversion

`test/scripts/.gen_random.py.swp`
`test/scripts/out.txt`

2017-10-05 20:47 UTC, LINKIWI commented on test/integration/ReplicationTest.cc
> +//        ASSERT_EQ(0, system("diff expected_testfile1234 actual_testfile1234 > /dev/null"));
Is this deliberate?

2017-10-05 21:35 UTC, rzhang0720 commented
unversioned:
`test/scripts/.gen_random.py.swp`
`test/scripts/out.txt`

added check back in testReadWrite in ReplicationTest

2017-10-05 21:41 UTC, rzhang0720 commented on test/integration/ReplicationTest.cc
> +//        ASSERT_EQ(0, system("diff expected_testfile1234 actual_testfile1234 > /dev/null"));
good catch, I changed it back

2017-10-06 16:06 UTC, LINKIWI approved these changes

2017-10-06 16:07 UTC, LINKIWI commented
approving to unblock - merge if CI is clean. I think this will merge cleanly

2017-10-06 18:33 UTC, merged